### ISSUE TITLE
Discourse relation

### ISSUE THREAD

**Issue by wt123u** [VioletPeng/GraphLSTM_release#1]
@VioletPeng 
Hi,
Thanks for sharing!  Is the discourse relation used in the code? If so, what is the markup? Since both the dependency relation and the discourse relation are dependencies in the data_graph, it is a little confusing about the discourse relation.

**Comment by VioletPeng** [comment]
Hi, as we discussed in the paper, the discourse relation wasn't included. We tried it in the early stage of the development and found it not useful (probably because it's too noisy)

**Comment by wt123u** [comment]
Hi,
Thank you for your quick reply. I would like to add discourse relation to cross-sentence relation extraction. Could you give me some suggestions? Since I find that performance degrades when dependency information is added, I want to try the discourse relation.
