### ISSUE TITLE
Positive-Negative Examples.

### ISSUE THREAD

**Issue by tahmedge** [VioletPeng/GraphLSTM_release#2]
Hi, I found in the "sentences_2nd" files that there are multiple labels (e.g., resistance or non-response, sensitivity, response, none). My first question is, did you do binary classifications?  If so, then which labels are considered as positive and which ones are considered as negative?

**Comment by VioletPeng** [comment]
Yes, we binarilized the label. 
if label == 'None':
                y = 0
else:
                y = 1

**Comment by tahmedge** [comment]
Thanks a lot.
